export const OPEN_MODAL = 'OPEN_MODAL';
export const TOGGLE_MENU_BTNS = 'TOGGLE_MENU_BTNS';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const UPDATE_INITIAL_STATE = 'UPDATE_INITIAL_STATE';
export const UPDATE_TEAM_PASSWORDS = 'UPDATE_TEAM_PASSWORDS';